ALTER TABLE tenant ADD COLUMN wizard_step VARCHAR(32) NOT NULL DEFAULT 'PROFILE';
ALTER TABLE tenant ADD COLUMN clock_mapping JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN tenant.wizard_step IS 'Onboarding wizard: PROFILE, LOCATIONS, PAY_PERIOD, JOB_CODES, PEOPLE, CLOCK, DESTINATION, POLICIES, DONE';
